<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends EntityRepository
{
    public function findProductsByName($name)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            'SELECT products 
            FROM ShopBundle:Products products WHERE
            products.name LIKE :name'
        )->setParameter('name', "%$name%");

        $books = $query->getResult();

        return $books;
    }

    public function findProductsByNameAndCategory($name, $category)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            'SELECT products 
            FROM ShopBundle:Products products 
            WHERE (products.name LIKE :name) 
            AND (products.category = :category)'
        )->setParameter('name', "%$name%")
        ->setParameter('category', $category);

        $books = $query->getResult();

        return $books;
    }
}
